import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { authService } from '../services/authService';
import {
  LogIn,
  AlertCircle,
  CheckCircle2,
  Loader2,
  ArrowLeft,
  Mail,
  Lock,
  GraduationCap,
  Eye,
  EyeOff,
  User,
  X,
  Sparkles,
  Award,
} from 'lucide-react';
import logoNiepmd from '../assets/logo_niepmd.jpg';

export default function LearnerLogin() {
  const navigate = useNavigate();
  const { loginUser } = useAuth();

  // Login States
  const [email, setEmail] = useState('learner@cat.com');
  const [password, setPassword] = useState('Password123!');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successData, setSuccessData] = useState(null);

  // Independent Learner Registration States (NO Learner ID input - generated by backend)
  const [isRegisterOpen, setIsRegisterOpen] = useState(false);
  const [regFullName, setRegFullName] = useState('');
  const [regEmail, setRegEmail] = useState('');
  const [regPassword, setRegPassword] = useState('');
  const [regConfirmPassword, setRegConfirmPassword] = useState('');
  const [registerLoading, setRegisterLoading] = useState(false);
  const [registerError, setRegisterError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!email || !password) {
      setError('Please enter email and password.');
      return;
    }

    setLoading(true);
    setError(null);
    setSuccessData(null);

    try {
      const res = await loginUser({ email, password });
      if (res.success) {
        if (res.data?.user?.role === 'learner') {
          navigate('/learner-dashboard');
        } else {
          setError('This account is not registered as a learner account.');
        }
      } else {
        setError(res.message || 'Authentication failed. Please verify credentials.');
        setPassword('');
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Login failed. Please verify your credentials.');
      setPassword('');
    } finally {
      setLoading(false);
    }
  };

  const handleLearnerRegister = async (e) => {
    e.preventDefault();

    if (
      !regFullName.trim() ||
      !regEmail.trim() ||
      !regPassword ||
      !regConfirmPassword
    ) {
      setRegisterError('All fields are required.');
      return;
    }

    if (regPassword !== regConfirmPassword) {
      setRegisterError('Passwords do not match.');
      return;
    }

    if (regPassword.length < 6) {
      setRegisterError('Password must be at least 6 characters.');
      return;
    }

    setRegisterLoading(true);
    setRegisterError(null);

    try {
      const res = await authService.register({
        fullName: regFullName.trim(),
        email: regEmail.trim(),
        password: regPassword,
        role: 'learner',
      });

      if (!res.success) {
        setRegisterError(res.message || 'Learner account creation failed.');
        return;
      }

      const generatedLearnerId = res.data?.user?.learnerId;

      // Registration successful: close modal & reset form
      setIsRegisterOpen(false);
      setRegFullName('');
      setRegEmail('');
      setRegPassword('');
      setRegConfirmPassword('');
      setRegisterError(null);

      // Pre-fill email on login form and display prominent success banner with generated Learner ID
      setEmail(regEmail.trim());
      setPassword('');
      setError(null);
      setSuccessData({
        learnerId: generatedLearnerId,
        email: regEmail.trim(),
      });
    } catch (err) {
      setRegisterError(
        err.response?.data?.message ||
        'Registration failed. Email might already be in use.'
      );
    } finally {
      setRegisterLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#ffffb3] text-slate-900 flex items-center justify-center p-4 md:p-8 font-sans selection:bg-purple-600 selection:text-white">
      <div className="bg-white rounded-2xl border-2 border-purple-200 shadow-2xl overflow-hidden max-w-4xl w-full grid grid-cols-1 md:grid-cols-2">
        
        {/* Left Side: NIEPMD Branding */}
        <div className="hidden md:flex flex-col justify-between bg-purple-50/60 p-10 relative border-r-2 border-purple-100">
          <div className="flex items-center gap-3">
            <img
              src={logoNiepmd}
              alt="NIEPMD"
              className="w-10 h-10 object-contain rounded-xl bg-white p-0.5 border border-purple-200"
            />
            <span className="font-black text-purple-950 text-lg tracking-tight">
              CAT Learner Portal
            </span>
          </div>

          <div className="my-8 text-center space-y-4">
            <div className="w-20 h-20 rounded-2xl bg-purple-100 border border-purple-300 text-purple-800 flex items-center justify-center mx-auto shadow-xs">
              <GraduationCap className="w-10 h-10" />
            </div>
            <h3 className="text-xl font-extrabold text-purple-950">Learner Portal</h3>
            <p className="text-xs text-purple-900 leading-relaxed max-w-xs mx-auto font-medium">
              Access communication activities, practice your skills, and track your learning progress at your own pace.
            </p>
          </div>

          <div className="text-[11px] text-purple-800 text-center font-bold">
            NIEPMD Official Learner Portal
          </div>
        </div>

        {/* Right Side: Form Section */}
        <div className="p-8 md:p-10 flex flex-col justify-between">
          <div>
            <button
              type="button"
              onClick={() => navigate('/')}
              className="inline-flex items-center gap-1.5 text-xs text-purple-900 hover:text-purple-700 transition-colors font-bold mb-6 cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Role Selection</span>
            </button>

            <div className="mb-6">
              <div className="flex items-center gap-1.5 text-purple-700 font-extrabold text-xs uppercase tracking-wider mb-1">
                <GraduationCap className="w-4 h-4 text-purple-700 fill-purple-700" />
                <span>Learner Access</span>
              </div>
              <h2 className="text-2xl font-black text-purple-950">Learner Sign In</h2>
              <p className="text-xs text-purple-800 mt-1 font-medium">
                Access your communication activities and learning progress
              </p>
            </div>

            {/* Error Banner */}
            {error && (
              <div className="mb-5 p-3 bg-red-50 border border-red-200 text-red-700 rounded-xl text-xs flex items-center gap-2 font-medium">
                <AlertCircle className="w-4 h-4 flex-shrink-0 text-red-500" />
                <span>{error}</span>
              </div>
            )}

            {/* Success Banner Showing Auto-Generated Learner ID */}
            {successData && (
              <div className="mb-5 p-4 bg-purple-50 border-2 border-purple-300 text-purple-950 rounded-2xl text-xs space-y-2 shadow-xs animate-fadeIn">
                <div className="flex items-center gap-2 font-extrabold text-purple-900">
                  <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0" />
                  <span>Account created successfully!</span>
                </div>
                {successData.learnerId && (
                  <div className="flex items-center justify-between bg-white border border-purple-200 p-2.5 rounded-xl">
                    <span className="font-semibold text-purple-800">Your Learner ID:</span>
                    <span className="font-mono font-black text-purple-900 bg-purple-100 px-2 py-0.5 rounded-lg text-xs">
                      {successData.learnerId}
                    </span>
                  </div>
                )}
                <p className="text-[11px] text-purple-700 font-medium">
                  Please sign in with your email and password.
                </p>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-purple-950 mb-1.5">
                  Email Address
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-purple-400">
                    <Mail className="w-4 h-4" />
                  </span>
                  <input
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="learner@cat.com"
                    className="w-full pl-10 pr-4 py-3 bg-purple-50/40 border border-purple-200 focus:border-purple-600 focus:ring-2 focus:ring-purple-100 rounded-xl text-xs text-purple-950 font-medium outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-purple-950 mb-1.5">
                  Password
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-purple-400">
                    <Lock className="w-4 h-4" />
                  </span>
                  <input
                    type={showPassword ? 'text' : 'password'}
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full pl-10 pr-10 py-3 bg-purple-50/40 border border-purple-200 focus:border-purple-600 focus:ring-2 focus:ring-purple-100 rounded-xl text-xs text-purple-950 font-medium outline-none"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute inset-y-0 right-0 pr-3.5 flex items-center text-purple-400 hover:text-purple-700"
                  >
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-3.5 mt-2 bg-purple-700 hover:bg-purple-800 text-white font-extrabold rounded-xl shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-white" />
                    <span>Signing in...</span>
                  </>
                ) : (
                  <>
                    <LogIn className="w-4 h-4" />
                    <span>Sign In</span>
                  </>
                )}
              </button>
            </form>

            <div className="mt-6 text-center text-xs text-purple-900 font-medium">
              <span>New Learner? </span>
              <button
                type="button"
                onClick={() => {
                  setIsRegisterOpen(true);
                  setRegisterError(null);
                }}
                className="font-extrabold text-purple-700 hover:underline cursor-pointer"
              >
                Create Account
              </button>
            </div>
          </div>

          <div className="mt-8 pt-4 border-t border-purple-100 text-center text-[11px] text-purple-800">
            <span className="font-semibold text-purple-950">Default Demo Credentials:</span>
            <div className="mt-1 font-mono text-purple-700 font-bold">
              learner@cat.com • Password123!
            </div>
          </div>
        </div>
      </div>

      {/* INDEPENDENT LEARNER REGISTRATION MODAL (No Learner ID input - Auto-generated) */}
      {isRegisterOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-purple-950/70 backdrop-blur-xs p-4 animate-fadeIn">
          <div className="bg-white border-2 border-purple-200 rounded-3xl shadow-2xl max-w-md w-full overflow-hidden relative p-6 sm:p-8 space-y-4">
            <button
              onClick={() => setIsRegisterOpen(false)}
              className="absolute top-5 right-5 p-1.5 rounded-xl text-purple-400 hover:text-purple-900 hover:bg-purple-100 transition-colors cursor-pointer"
              aria-label="Close registration modal"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="text-center">
              <div className="w-12 h-12 rounded-2xl bg-purple-100 border border-purple-200 text-purple-700 flex items-center justify-center mx-auto mb-2 shadow-xs">
                <GraduationCap className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-black text-purple-950">Create Learner Account</h3>
              <p className="text-xs text-purple-800 mt-1 font-medium">
                Enter your details below. Your Learner ID will be automatically generated upon registration.
              </p>
            </div>

            {registerError && (
              <div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-xl text-xs flex items-center gap-2 font-medium">
                <AlertCircle className="w-4 h-4 flex-shrink-0 text-red-500" />
                <span>{registerError}</span>
              </div>
            )}

            <form onSubmit={handleLearnerRegister} className="space-y-3.5 text-xs">
              <div>
                <label className="block text-purple-950 font-bold mb-1">
                  Full Name
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-purple-400">
                    <User className="w-4 h-4" />
                  </span>
                  <input
                    type="text"
                    required
                    value={regFullName}
                    onChange={(e) => setRegFullName(e.target.value)}
                    placeholder="Alex Carter"
                    className="w-full pl-9 pr-3 py-2.5 bg-purple-50/40 border border-purple-200 rounded-xl text-purple-950 outline-none focus:border-purple-600 focus:ring-2 focus:ring-purple-100 font-medium"
                  />
                </div>
              </div>

              <div>
                <label className="block text-purple-950 font-bold mb-1">
                  Email Address
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-purple-400">
                    <Mail className="w-4 h-4" />
                  </span>
                  <input
                    type="email"
                    required
                    value={regEmail}
                    onChange={(e) => setRegEmail(e.target.value)}
                    placeholder="alex@example.com"
                    className="w-full pl-9 pr-3 py-2.5 bg-purple-50/40 border border-purple-200 rounded-xl text-purple-950 outline-none focus:border-purple-600 focus:ring-2 focus:ring-purple-100 font-medium"
                  />
                </div>
              </div>

              <div>
                <label className="block text-purple-950 font-bold mb-1">
                  Password
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-purple-400">
                    <Lock className="w-4 h-4" />
                  </span>
                  <input
                    type="password"
                    required
                    value={regPassword}
                    onChange={(e) => setRegPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full pl-9 pr-3 py-2.5 bg-purple-50/40 border border-purple-200 rounded-xl text-purple-950 outline-none focus:border-purple-600 focus:ring-2 focus:ring-purple-100 font-medium"
                  />
                </div>
              </div>

              <div>
                <label className="block text-purple-950 font-bold mb-1">
                  Confirm Password
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-purple-400">
                    <Lock className="w-4 h-4" />
                  </span>
                  <input
                    type="password"
                    required
                    value={regConfirmPassword}
                    onChange={(e) => setRegConfirmPassword(e.target.value)}
                    placeholder="••••••••"
                    className="w-full pl-9 pr-3 py-2.5 bg-purple-50/40 border border-purple-200 rounded-xl text-purple-950 outline-none focus:border-purple-600 focus:ring-2 focus:ring-purple-100 font-medium"
                  />
                </div>
              </div>

              <div className="pt-2">
                <button
                  type="submit"
                  disabled={registerLoading}
                  className="w-full py-3 bg-purple-700 hover:bg-purple-800 text-white font-extrabold rounded-xl shadow-md transition-all cursor-pointer disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {registerLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin text-white" />
                      <span>Creating Account...</span>
                    </>
                  ) : (
                    <span>Create Learner Account</span>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
